//Mock data used for the frontend development in the initial phase before the Alpha Vantage API was integrated


// An array of Details of some Stock 
export const mockSearchResults = 
    [{
        "Symbol": "WMT",
        "AssetType": "Common Stock",
        "Name": "Walmart Inc",
        "Description": "Walmart Inc. is an American multinational retail corporation that operates a chain of hypermarkets, discount department stores, and grocery stores from the United States, headquartered in Bentonville, Arkansas. It also owns and operates Sam's Club retail warehouses.",
        "CIK": "104169",
        "Exchange": "NYSE",
        "Currency": "USD",
        "Country": "USA",
        "Sector": "TRADE & SERVICES",
        "Industry": "RETAIL-VARIETY STORES",
        "Address": "702 SOUTHWEST 8TH ST, BENTONVILLE, AR, US",
        "FiscalYearEnd": "January",
        "LatestQuarter": "2024-01-31",
        "MarketCapitalization": "487456080000",
        "EBITDA": "38864998000",
        "PERatio": "31.66",
        "PEGRatio": "2.438",
        "BookValue": "10.41",
        "DividendPerShare": "0.76",
        "DividendYield": "0.0137",
        "EPS": "1.91",
        "RevenuePerShareTTM": "80.24",
        "ProfitMargin": "0.0239",
        "OperatingMarginTTM": "0.0418",
        "ReturnOnAssetsTTM": "0.0681",
        "ReturnOnEquityTTM": "0.186",
        "RevenueTTM": "648125022000",
        "GrossProfitTTM": "147568000000",
        "DilutedEPSTTM": "1.91",
        "QuarterlyEarningsGrowthYOY": "-0.124",
        "QuarterlyRevenueGrowthYOY": "0.057",
        "AnalystTargetPrice": "66.01",
        "AnalystRatingStrongBuy": "12",
        "AnalystRatingBuy": "25",
        "AnalystRatingHold": "4",
        "AnalystRatingSell": "0",
        "AnalystRatingStrongSell": "0",
        "TrailingPE": "31.66",
        "ForwardPE": "25.13",
        "PriceToSalesRatioTTM": "0.735",
        "PriceToBookRatio": "5.68",
        "EVToRevenue": "0.814",
        "EVToEBITDA": "14.5",
        "Beta": "0.494",
        "52WeekHigh": "61.66",
        "52WeekLow": "47.82",
        "50DayMovingAverage": "60.14",
        "200DayMovingAverage": "55.43",
        "SharesOutstanding": "8059790000",
        "DividendDate": "2025-01-06",
        "ExDividendDate": "2024-08-15"
},
{
    "Symbol": "IBM",
    "AssetType": "Common Stock",
    "Name": "International Business Machines",
    "Description": "International Business Machines Corporation (IBM) is an American multinational technology company headquartered in Armonk, New York, with operations in over 170 countries. The company began in 1911, founded in Endicott, New York, as the Computing-Tabulating-Recording Company (CTR) and was renamed International Business Machines in 1924. IBM is incorporated in New York. IBM produces and sells computer hardware, middleware and software, and provides hosting and consulting services in areas ranging from mainframe computers to nanotechnology. IBM is also a major research organization, holding the record for most annual U.S. patents generated by a business (as of 2020) for 28 consecutive years. Inventions by IBM include the automated teller machine (ATM), the floppy disk, the hard disk drive, the magnetic stripe card, the relational database, the SQL programming language, the UPC barcode, and dynamic random-access memory (DRAM). The IBM mainframe, exemplified by the System/360, was the dominant computing platform during the 1960s and 1970s.",
    "CIK": "51143",
    "Exchange": "NYSE",
    "Currency": "USD",
    "Country": "USA",
    "Sector": "TECHNOLOGY",
    "Industry": "COMPUTER & OFFICE EQUIPMENT",
    "Address": "1 NEW ORCHARD ROAD, ARMONK, NY, US",
    "FiscalYearEnd": "December",
    "LatestQuarter": "2024-03-31",
    "MarketCapitalization": "153920995000",
    "EBITDA": "14380000000",
    "PERatio": "18.98",
    "PEGRatio": "4.2",
    "BookValue": "25.32",
    "DividendPerShare": "6.64",
    "DividendYield": "0.0399",
    "EPS": "8.82",
    "RevenuePerShareTTM": "67.94",
    "ProfitMargin": "0.132",
    "OperatingMarginTTM": "0.102",
    "ReturnOnAssetsTTM": "0.0458",
    "ReturnOnEquityTTM": "0.362",
    "RevenueTTM": "62068998000",
    "GrossProfitTTM": "32688000000",
    "DilutedEPSTTM": "8.82",
    "QuarterlyEarningsGrowthYOY": "0.701",
    "QuarterlyRevenueGrowthYOY": "0.015",
    "AnalystTargetPrice": "181.57",
    "AnalystRatingStrongBuy": "4",
    "AnalystRatingBuy": "4",
    "AnalystRatingHold": "10",
    "AnalystRatingSell": "3",
    "AnalystRatingStrongSell": "0",
    "TrailingPE": "18.98",
    "ForwardPE": "18.12",
    "PriceToSalesRatioTTM": "2.701",
    "PriceToBookRatio": "7.42",
    "EVToRevenue": "3.453",
    "EVToEBITDA": "14.54",
    "Beta": "0.745",
    "52WeekHigh": "199.18",
    "52WeekLow": "121.1",
    "50DayMovingAverage": "183.02",
    "200DayMovingAverage": "163.51",
    "SharesOutstanding": "918603000",
    "DividendDate": "2024-06-10",
    "ExDividendDate": "2024-05-09"
},
{
    "Symbol": "MSFT",
    "AssetType": "Common Stock",
    "Name": "Microsoft Corporation",
    "Description": "Microsoft Corporation is an American multinational technology company which produces computer software, consumer electronics, personal computers, and related services. Its best known software products are the Microsoft Windows line of operating systems, the Microsoft Office suite, and the Internet Explorer and Edge web browsers. Its flagship hardware products are the Xbox video game consoles and the Microsoft Surface lineup of touchscreen personal computers. Microsoft ranked No. 21 in the 2020 Fortune 500 rankings of the largest United States corporations by total revenue; it was the world's largest software maker by revenue as of 2016. It is considered one of the Big Five companies in the U.S. information technology industry, along with Google, Apple, Amazon, and Facebook.",
    "CIK": "789019",
    "Exchange": "NASDAQ",
    "Currency": "USD",
    "Country": "USA",
    "Sector": "TECHNOLOGY",
    "Industry": "SERVICES-PREPACKAGED SOFTWARE",
    "Address": "ONE MICROSOFT WAY, REDMOND, WA, US",
    "FiscalYearEnd": "June",
    "LatestQuarter": "2024-03-31",
    "MarketCapitalization": "3197082272000",
    "EBITDA": "125182001000",
    "PERatio": "37.31",
    "PEGRatio": "2.024",
    "BookValue": "34.06",
    "DividendPerShare": "2.93",
    "DividendYield": "0.007",
    "EPS": "11.53",
    "RevenuePerShareTTM": "31.83",
    "ProfitMargin": "0.364",
    "OperatingMarginTTM": "0.446",
    "ReturnOnAssetsTTM": "0.153",
    "ReturnOnEquityTTM": "0.385",
    "RevenueTTM": "236583993000",
    "GrossProfitTTM": "135620000000",
    "DilutedEPSTTM": "11.53",
    "QuarterlyEarningsGrowthYOY": "0.2",
    "QuarterlyRevenueGrowthYOY": "0.17",
    "AnalystTargetPrice": "445.02",
    "AnalystRatingStrongBuy": "23",
    "AnalystRatingBuy": "32",
    "AnalystRatingHold": "3",
    "AnalystRatingSell": "0",
    "AnalystRatingStrongSell": "0",
    "TrailingPE": "37.31",
    "ForwardPE": "29.94",
    "PriceToSalesRatioTTM": "13.03",
    "PriceToBookRatio": "12.45",
    "EVToRevenue": "13.06",
    "EVToEBITDA": "24.59",
    "Beta": "0.893",
    "52WeekHigh": "433.6",
    "52WeekLow": "307.7",
    "50DayMovingAverage": "416.27",
    "200DayMovingAverage": "376.97",
    "SharesOutstanding": "7432310000",
    "DividendDate": "2024-06-13",
    "ExDividendDate": "2024-05-15"
},
{
    "Symbol": "JPM",
    "AssetType": "Common Stock",
    "Name": "JPMorgan Chase & Co",
    "Description": "JPMorgan Chase & Co. is an American multinational investment bank and financial services holding company headquartered in New York City. JPMorgan Chase is incorporated in Delaware. As a Bulge Bracket bank, it is a major provider of various investment banking and financial services. It is one of America's Big Four banks, along with Bank of America, Citigroup, and Wells Fargo. JPMorgan Chase is considered to be a universal bank and a custodian bank. The J.P. Morgan brand is used by the investment banking, asset management, private banking, private wealth management, and treasury services divisions.",
    "CIK": "19617",
    "Exchange": "NYSE",
    "Currency": "USD",
    "Country": "USA",
    "Sector": "FINANCE",
    "Industry": "NATIONAL COMMERCIAL BANKS",
    "Address": "383 MADISON AVENUE, NEW YORK, NY, US",
    "FiscalYearEnd": "December",
    "LatestQuarter": "2024-03-31",
    "MarketCapitalization": "576372933000",
    "EBITDA": "None",
    "PERatio": "12.11",
    "PEGRatio": "3.356",
    "BookValue": "106.81",
    "DividendPerShare": "4.25",
    "DividendYield": "0.0229",
    "EPS": "16.58",
    "RevenuePerShareTTM": "51.31",
    "ProfitMargin": "0.336",
    "OperatingMarginTTM": "0.452",
    "ReturnOnAssetsTTM": "0.0129",
    "ReturnOnEquityTTM": "0.157",
    "RevenueTTM": "150000992000",
    "GrossProfitTTM": "122306000000",
    "DilutedEPSTTM": "16.58",
    "QuarterlyEarningsGrowthYOY": "0.083",
    "QuarterlyRevenueGrowthYOY": "0.111",
    "AnalystTargetPrice": "192.19",
    "AnalystRatingStrongBuy": "7",
    "AnalystRatingBuy": "13",
    "AnalystRatingHold": "7",
    "AnalystRatingSell": "0",
    "AnalystRatingStrongSell": "0",
    "TrailingPE": "12.11",
    "ForwardPE": "11.39",
    "PriceToSalesRatioTTM": "3.596",
    "PriceToBookRatio": "1.747",
    "EVToRevenue": "-",
    "EVToEBITDA": "-",
    "Beta": "1.116",
    "52WeekHigh": "205.88",
    "52WeekLow": "130.93",
    "50DayMovingAverage": "194.51",
    "200DayMovingAverage": "168.2",
    "SharesOutstanding": "2871670000",
    "DividendDate": "2024-04-30",
    "ExDividendDate": "2024-07-05"
},
{
    "Symbol": "GOOG",
    "AssetType": "Common Stock",
    "Name": "Alphabet Inc Class C",
    "Description": "Alphabet Inc. is an American multinational conglomerate headquartered in Mountain View, California. It was created through a restructuring of Google on October 2, 2015, and became the parent company of Google and several former Google subsidiaries. The two co-founders of Google remained as controlling shareholders, board members, and employees at Alphabet. Alphabet is the world's fourth-largest technology company by revenue and one of the world's most valuable companies.",
    "CIK": "1652044",
    "Exchange": "NASDAQ",
    "Currency": "USD",
    "Country": "USA",
    "Sector": "TECHNOLOGY",
    "Industry": "SERVICES-COMPUTER PROGRAMMING, DATA PROCESSING, ETC.",
    "Address": "1600 AMPHITHEATRE PARKWAY, MOUNTAIN VIEW, CA, US",
    "FiscalYearEnd": "December",
    "LatestQuarter": "2024-03-31",
    "MarketCapitalization": "2170058047000",
    "EBITDA": "109723001000",
    "PERatio": "27.04",
    "PEGRatio": "1.659",
    "BookValue": "23.65",
    "DividendPerShare": "None",
    "DividendYield": "None",
    "EPS": "6.52",
    "RevenuePerShareTTM": "25.37",
    "ProfitMargin": "0.259",
    "OperatingMarginTTM": "0.325",
    "ReturnOnAssetsTTM": "0.156",
    "ReturnOnEquityTTM": "0.298",
    "RevenueTTM": "318145987000",
    "GrossProfitTTM": "156633000000",
    "DilutedEPSTTM": "6.52",
    "QuarterlyEarningsGrowthYOY": "0.609",
    "QuarterlyRevenueGrowthYOY": "0.154",
    "AnalystTargetPrice": "170.44",
    "AnalystRatingStrongBuy": "6",
    "AnalystRatingBuy": "7",
    "AnalystRatingHold": "3",
    "AnalystRatingSell": "0",
    "AnalystRatingStrongSell": "0",
    "TrailingPE": "27.04",
    "ForwardPE": "23.42",
    "PriceToSalesRatioTTM": "6.41",
    "PriceToBookRatio": "6.99",
    "EVToRevenue": "6.14",
    "EVToEBITDA": "19.27",
    "Beta": "1.019",
    "52WeekHigh": "179.95",
    "52WeekLow": "115.83",
    "50DayMovingAverage": "162.07",
    "200DayMovingAverage": "143.85",
    "SharesOutstanding": "5617000000",
    "DividendDate": "2024-06-17",
    "ExDividendDate": "2024-06-10"
}]
    
    
// Details of a company 

   export const mockCompanyDetials = {
    "Symbol": "WMT",
    "AssetType": "Common Stock",
    "Name": "Walmart Inc",
    "Description": "Walmart Inc. is an American multinational retail corporation that operates a chain of hypermarkets, discount department stores, and grocery stores from the United States, headquartered in Bentonville, Arkansas. It also owns and operates Sam's Club retail warehouses.",
    "CIK": "104169",
    "Exchange": "NYSE",
    "Currency": "USD",
    "Country": "USA",
    "Sector": "TRADE & SERVICES",
    "Industry": "RETAIL-VARIETY STORES",
    "Address": "702 SOUTHWEST 8TH ST, BENTONVILLE, AR, US",
    "FiscalYearEnd": "January",
    "LatestQuarter": "2024-01-31",
    "MarketCapitalization": "487456080000",
    "EBITDA": "38864998000",
    "PERatio": "31.66",
    "PEGRatio": "2.438",
    "BookValue": "10.41",
    "DividendPerShare": "0.76",
    "DividendYield": "0.0137",
    "EPS": "1.91",
    "RevenuePerShareTTM": "80.24",
    "ProfitMargin": "0.0239",
    "OperatingMarginTTM": "0.0418",
    "ReturnOnAssetsTTM": "0.0681",
    "ReturnOnEquityTTM": "0.186",
    "RevenueTTM": "648125022000",
    "GrossProfitTTM": "147568000000",
    "DilutedEPSTTM": "1.91",
    "QuarterlyEarningsGrowthYOY": "-0.124",
    "QuarterlyRevenueGrowthYOY": "0.057",
    "AnalystTargetPrice": "66.01",
    "AnalystRatingStrongBuy": "12",
    "AnalystRatingBuy": "25",
    "AnalystRatingHold": "4",
    "AnalystRatingSell": "0",
    "AnalystRatingStrongSell": "0",
    "TrailingPE": "31.66",
    "ForwardPE": "25.13",
    "PriceToSalesRatioTTM": "0.735",
    "PriceToBookRatio": "5.68",
    "EVToRevenue": "0.814",
    "EVToEBITDA": "14.5",
    "Beta": "0.494",
    "52WeekHigh": "61.66",
    "52WeekLow": "47.82",
    "50DayMovingAverage": "60.14",
    "200DayMovingAverage": "55.43",
    "SharesOutstanding": "8059790000",
    "DividendDate": "2025-01-06",
    "ExDividendDate": "2024-08-15"
   }

   // mock stock quotes of some companies 

   export const mockStockQuote =[
    {
        "01. symbol": "WMT",
        "02. open": "60.6200",
        "03. high": "61.3450",
        "04. low": "60.2900",
        "05. price": "60.4100",
        "06. volume": "19260522",
        "07. latest trading day": "2024-05-13",
        "08. previous close": "60.4800",
        "09. change": "-0.0700",
        "10. change percent": "-0.1157%"
    },
    {
        "01. symbol": "IBM",
        "02. open": "60.6200",
        "03. high": "61.3450",
        "04. low": "60.2900",
        "05. price": "30.4100",
        "06. volume": "19260522",
        "07. latest trading day": "2024-05-13",
        "08. previous close": "60.4800",
        "09. change": "0.15900",
        "10. change percent": "0.1257%"
    },

    {
        "01. symbol": "GOOG",
        "02. open": "60.6200",
        "03. high": "61.3450",
        "04. low": "60.2900",
        "05. price": "600.4100",
        "06. volume": "19260522",
        "07. latest trading day": "2024-05-13",
        "08. previous close": "60.4800",
        "09. change": "0.0700",
        "10. change percent": "0.1157%"
    },
    {
        "01. symbol": "MSFT",
        "02. open": "60.6200",
        "03. high": "61.3450",
        "04. low": "60.2900",
        "05. price": "30.4100",
        "06. volume": "19260522",
        "07. latest trading day": "2024-05-13",
        "08. previous close": "60.4800",
        "09. change": "-0.0900",
        "10. change percent": "-0.1257%"
    },
  
    {
        "01. symbol": "JPM",
        "02. open": "60.6200",
        "03. high": "61.3450",
        "04. low": "60.2900",
        "05. price": "30.4100",
        "06. volume": "19260522",
        "07. latest trading day": "2024-05-13",
        "08. previous close": "60.4800",
        "09. change": "0.25900",
        "10. change percent": "0.1579%"
    }


]

export const mockWishlist = [
    {
        "01. symbol": "WMT",
        "02. open": "60.6200",
        "03. high": "61.3450",
        "04. low": "60.2900",
        "05. price": "60.4100",
        "06. volume": "19260522",
        "07. latest trading day": "2024-05-13",
        "08. previous close": "60.4800",
        "09. change": "-0.0700",
        "10. change percent": "-0.1157%"
    },

    {
        "01. symbol": "GOOG",
        "02. open": "60.6200",
        "03. high": "61.3450",
        "04. low": "60.2900",
        "05. price": "600.4100",
        "06. volume": "19260522",
        "07. latest trading day": "2024-05-13",
        "08. previous close": "60.4800",
        "09. change": "0.0700",
        "10. change percent": "0.1157%"
    },
    {
        "01. symbol": "MSFT",
        "02. open": "60.6200",
        "03. high": "61.3450",
        "04. low": "60.2900",
        "05. price": "30.4100",
        "06. volume": "19260522",
        "07. latest trading day": "2024-05-13",
        "08. previous close": "60.4800",
        "09. change": "-0.0900",
        "10. change percent": "-0.1257%"
    },
  
    {
        "01. symbol": "JPM",
        "02. open": "60.6200",
        "03. high": "61.3450",
        "04. low": "60.2900",
        "05. price": "30.4100",
        "06. volume": "19260522",
        "07. latest trading day": "2024-05-13",
        "08. previous close": "60.4800",
        "09. change": "0.25900",
        "10. change percent": "0.1579%"
    }
]

// mock historial data of a a company 

export const mockHistoricalData ={
    "Meta Data": {
        "1. Information": "Intraday (60min) open, high, low, close prices and volume",
        "2. Symbol": "IBM",
        "3. Last Refreshed": "2024-05-14 19:00:00",
        "4. Interval": "60min",
        "5. Output Size": "Compact",
        "6. Time Zone": "US/Eastern"
    },
    "Time Series (60min)": {
        "2024-05-14 19:00:00": {
            "1. open": "167.3600",
            "2. high": "167.5900",
            "3. low": "167.3600",
            "4. close": "167.3800",
            "5. volume": "415265"
        },
        "2024-05-14 18:00:00": {
            "1. open": "167.5900",
            "2. high": "167.5900",
            "3. low": "167.1700",
            "4. close": "167.1700",
            "5. volume": "415324"
        },
        "2024-05-14 17:00:00": {
            "1. open": "167.2800",
            "2. high": "167.5250",
            "3. low": "167.2300",
            "4. close": "167.2300",
            "5. volume": "184"
        },
        "2024-05-14 16:00:00": {
            "1. open": "167.3400",
            "2. high": "167.6000",
            "3. low": "166.4800",
            "4. close": "167.5900",
            "5. volume": "1306073"
        },
        "2024-05-14 15:00:00": {
            "1. open": "167.4850",
            "2. high": "167.8600",
            "3. low": "167.1700",
            "4. close": "167.3400",
            "5. volume": "638448"
        },
        "2024-05-14 14:00:00": {
            "1. open": "166.7260",
            "2. high": "167.6800",
            "3. low": "166.7260",
            "4. close": "167.4850",
            "5. volume": "204752"
        },
        "2024-05-14 13:00:00": {
            "1. open": "166.8200",
            "2. high": "166.9200",
            "3. low": "166.4800",
            "4. close": "166.7100",
            "5. volume": "303413"
        },
        "2024-05-14 12:00:00": {
            "1. open": "166.8800",
            "2. high": "166.9400",
            "3. low": "166.5800",
            "4. close": "166.8550",
            "5. volume": "286929"
        },
        "2024-05-14 11:00:00": {
            "1. open": "167.2900",
            "2. high": "167.3100",
            "3. low": "166.7600",
            "4. close": "166.8510",
            "5. volume": "250760"
        },
        "2024-05-14 10:00:00": {
            "1. open": "167.5900",
            "2. high": "167.9600",
            "3. low": "167.1200",
            "4. close": "167.2470",
            "5. volume": "255146"
        },
        "2024-05-14 09:00:00": {
            "1. open": "167.1300",
            "2. high": "168.1300",
            "3. low": "167.0100",
            "4. close": "167.5400",
            "5. volume": "184241"
        },
        "2024-05-14 08:00:00": {
            "1. open": "167.7680",
            "2. high": "168.1900",
            "3. low": "166.8000",
            "4. close": "167.5400",
            "5. volume": "1076"
        },
        "2024-05-14 07:00:00": {
            "1. open": "167.4900",
            "2. high": "167.7400",
            "3. low": "167.4900",
            "4. close": "167.7400",
            "5. volume": "79"
        },
        "2024-05-14 06:00:00": {
            "1. open": "167.1600",
            "2. high": "167.7100",
            "3. low": "167.1600",
            "4. close": "167.4200",
            "5. volume": "3"
        },
        "2024-05-14 05:00:00": {
            "1. open": "167.5600",
            "2. high": "167.6300",
            "3. low": "167.1900",
            "4. close": "167.1900",
            "5. volume": "38"
        },
        "2024-05-14 04:00:00": {
            "1. open": "168.0000",
            "2. high": "168.0000",
            "3. low": "167.5200",
            "4. close": "167.6700",
            "5. volume": "9"
        },
        "2024-05-13 19:00:00": {
            "1. open": "167.5600",
            "2. high": "167.6400",
            "3. low": "167.3500",
            "4. close": "167.6400",
            "5. volume": "473356"
        },
        "2024-05-13 18:00:00": {
            "1. open": "167.6400",
            "2. high": "167.6400",
            "3. low": "167.3500",
            "4. close": "167.5400",
            "5. volume": "473149"
        },
        "2024-05-13 17:00:00": {
            "1. open": "166.9000",
            "2. high": "167.6400",
            "3. low": "166.9000",
            "4. close": "167.6400",
            "5. volume": "268"
        },
        "2024-05-13 16:00:00": {
            "1. open": "167.5200",
            "2. high": "167.6400",
            "3. low": "166.8000",
            "4. close": "166.9000",
            "5. volume": "1507707"
        },
        "2024-05-13 15:00:00": {
            "1. open": "167.3850",
            "2. high": "167.6000",
            "3. low": "167.2600",
            "4. close": "167.5200",
            "5. volume": "465614"
        },
        "2024-05-13 14:00:00": {
            "1. open": "167.2300",
            "2. high": "167.5200",
            "3. low": "167.0600",
            "4. close": "167.3850",
            "5. volume": "212671"
        },
        "2024-05-13 13:00:00": {
            "1. open": "167.1200",
            "2. high": "167.2600",
            "3. low": "166.7600",
            "4. close": "167.2500",
            "5. volume": "152728"
        },
        "2024-05-13 12:00:00": {
            "1. open": "167.3800",
            "2. high": "167.5400",
            "3. low": "167.1300",
            "4. close": "167.1400",
            "5. volume": "238865"
        },
        "2024-05-13 11:00:00": {
            "1. open": "167.5050",
            "2. high": "167.6900",
            "3. low": "167.2150",
            "4. close": "167.4000",
            "5. volume": "257408"
        },
        "2024-05-13 10:00:00": {
            "1. open": "167.5900",
            "2. high": "167.8500",
            "3. low": "167.3400",
            "4. close": "167.4900",
            "5. volume": "297631"
        },
        "2024-05-13 09:00:00": {
            "1. open": "167.3500",
            "2. high": "168.0600",
            "3. low": "167.2600",
            "4. close": "167.6300",
            "5. volume": "223463"
        },
        "2024-05-13 08:00:00": {
            "1. open": "167.0000",
            "2. high": "167.4600",
            "3. low": "166.8900",
            "4. close": "167.4500",
            "5. volume": "1747"
        },
        "2024-05-13 07:00:00": {
            "1. open": "167.1500",
            "2. high": "167.5000",
            "3. low": "166.9000",
            "4. close": "167.4000",
            "5. volume": "2259"
        },
        "2024-05-13 06:00:00": {
            "1. open": "167.4400",
            "2. high": "167.6000",
            "3. low": "167.1500",
            "4. close": "167.1500",
            "5. volume": "240"
        },
        "2024-05-13 05:00:00": {
            "1. open": "167.1500",
            "2. high": "167.6900",
            "3. low": "167.1500",
            "4. close": "167.4400",
            "5. volume": "281"
        },
        "2024-05-13 04:00:00": {
            "1. open": "167.0600",
            "2. high": "167.2200",
            "3. low": "167.0600",
            "4. close": "167.1500",
            "5. volume": "169"
        },
        "2024-05-10 19:00:00": {
            "1. open": "167.1500",
            "2. high": "167.1500",
            "3. low": "167.0300",
            "4. close": "167.0500",
            "5. volume": "426057"
        },
        "2024-05-10 18:00:00": {
            "1. open": "167.1500",
            "2. high": "167.1500",
            "3. low": "167.0400",
            "4. close": "167.1300",
            "5. volume": "426601"
        },
        "2024-05-10 17:00:00": {
            "1. open": "167.0400",
            "2. high": "167.2000",
            "3. low": "167.0300",
            "4. close": "167.0300",
            "5. volume": "81"
        },
        "2024-05-10 16:00:00": {
            "1. open": "167.1200",
            "2. high": "167.4500",
            "3. low": "167.0200",
            "4. close": "167.1300",
            "5. volume": "1352615"
        },
        "2024-05-10 15:00:00": {
            "1. open": "166.9490",
            "2. high": "167.2400",
            "3. low": "166.7700",
            "4. close": "167.1200",
            "5. volume": "532901"
        },
        "2024-05-10 14:00:00": {
            "1. open": "166.9500",
            "2. high": "167.0550",
            "3. low": "166.7200",
            "4. close": "166.9200",
            "5. volume": "169895"
        },
        "2024-05-10 13:00:00": {
            "1. open": "166.7400",
            "2. high": "167.0200",
            "3. low": "166.5200",
            "4. close": "166.9400",
            "5. volume": "162244"
        },
        "2024-05-10 12:00:00": {
            "1. open": "166.5050",
            "2. high": "166.7850",
            "3. low": "166.3200",
            "4. close": "166.7200",
            "5. volume": "160178"
        },
        "2024-05-10 11:00:00": {
            "1. open": "167.0800",
            "2. high": "167.1050",
            "3. low": "166.3200",
            "4. close": "166.5200",
            "5. volume": "212883"
        },
        "2024-05-10 10:00:00": {
            "1. open": "167.5100",
            "2. high": "167.5600",
            "3. low": "166.6800",
            "4. close": "167.0460",
            "5. volume": "265778"
        },
        "2024-05-10 09:00:00": {
            "1. open": "166.4500",
            "2. high": "168.0700",
            "3. low": "166.2500",
            "4. close": "167.6200",
            "5. volume": "246110"
        },
        "2024-05-10 08:00:00": {
            "1. open": "166.9600",
            "2. high": "166.9700",
            "3. low": "166.2700",
            "4. close": "166.5100",
            "5. volume": "2753"
        },
        "2024-05-10 07:00:00": {
            "1. open": "166.7600",
            "2. high": "166.8500",
            "3. low": "166.6100",
            "4. close": "166.7700",
            "5. volume": "417"
        },
        "2024-05-10 06:00:00": {
            "1. open": "166.7500",
            "2. high": "166.8600",
            "3. low": "166.5500",
            "4. close": "166.8600",
            "5. volume": "266"
        },
        "2024-05-10 05:00:00": {
            "1. open": "166.5000",
            "2. high": "166.7500",
            "3. low": "166.4500",
            "4. close": "166.5600",
            "5. volume": "195"
        },
        "2024-05-10 04:00:00": {
            "1. open": "166.3900",
            "2. high": "166.6200",
            "3. low": "166.1400",
            "4. close": "166.2700",
            "5. volume": "538"
        },
        "2024-05-09 19:00:00": {
            "1. open": "166.2700",
            "2. high": "166.5000",
            "3. low": "166.0400",
            "4. close": "166.4300",
            "5. volume": "730413"
        },
        "2024-05-09 18:00:00": {
            "1. open": "166.2000",
            "2. high": "166.4900",
            "3. low": "166.1000",
            "4. close": "166.4900",
            "5. volume": "730661"
        },
        "2024-05-09 17:00:00": {
            "1. open": "166.2800",
            "2. high": "166.5000",
            "3. low": "166.1000",
            "4. close": "166.1370",
            "5. volume": "3939"
        },
        "2024-05-09 16:00:00": {
            "1. open": "166.3200",
            "2. high": "166.5300",
            "3. low": "165.9100",
            "4. close": "166.2200",
            "5. volume": "2527082"
        },
        "2024-05-09 15:00:00": {
            "1. open": "166.4400",
            "2. high": "166.7270",
            "3. low": "166.0100",
            "4. close": "166.3200",
            "5. volume": "974019"
        },
        "2024-05-09 14:00:00": {
            "1. open": "165.9950",
            "2. high": "166.4900",
            "3. low": "165.9300",
            "4. close": "166.4300",
            "5. volume": "339329"
        },
        "2024-05-09 13:00:00": {
            "1. open": "166.2700",
            "2. high": "166.5100",
            "3. low": "165.8800",
            "4. close": "166.0030",
            "5. volume": "499977"
        },
        "2024-05-09 12:00:00": {
            "1. open": "166.5500",
            "2. high": "166.6800",
            "3. low": "166.1650",
            "4. close": "166.2800",
            "5. volume": "313099"
        },
        "2024-05-09 11:00:00": {
            "1. open": "166.6800",
            "2. high": "167.1090",
            "3. low": "166.3200",
            "4. close": "166.5300",
            "5. volume": "268726"
        },
        "2024-05-09 10:00:00": {
            "1. open": "166.3220",
            "2. high": "167.3180",
            "3. low": "166.3220",
            "4. close": "166.6990",
            "5. volume": "384366"
        },
        "2024-05-09 09:00:00": {
            "1. open": "167.8500",
            "2. high": "168.1900",
            "3. low": "166.2900",
            "4. close": "166.3500",
            "5. volume": "406689"
        },
        "2024-05-09 08:00:00": {
            "1. open": "168.2300",
            "2. high": "170.5300",
            "3. low": "167.4600",
            "4. close": "167.8500",
            "5. volume": "12613"
        },
        "2024-05-09 07:00:00": {
            "1. open": "168.9700",
            "2. high": "168.9900",
            "3. low": "168.0000",
            "4. close": "168.0000",
            "5. volume": "1169"
        },
        "2024-05-09 06:00:00": {
            "1. open": "168.9500",
            "2. high": "168.9900",
            "3. low": "168.3000",
            "4. close": "168.3500",
            "5. volume": "66"
        },
        "2024-05-09 05:00:00": {
            "1. open": "168.3000",
            "2. high": "168.3500",
            "3. low": "168.2800",
            "4. close": "168.3500",
            "5. volume": "63"
        },
        "2024-05-09 04:00:00": {
            "1. open": "169.9300",
            "2. high": "169.9300",
            "3. low": "168.3000",
            "4. close": "168.3000",
            "5. volume": "29"
        },
        "2024-05-08 19:00:00": {
            "1. open": "168.2470",
            "2. high": "168.3550",
            "3. low": "168.2310",
            "4. close": "168.3300",
            "5. volume": "495614"
        },
        "2024-05-08 18:00:00": {
            "1. open": "168.2170",
            "2. high": "168.3550",
            "3. low": "168.1510",
            "4. close": "168.1510",
            "5. volume": "492045"
        },
        "2024-05-08 17:00:00": {
            "1. open": "168.2660",
            "2. high": "168.3460",
            "3. low": "168.0430",
            "4. close": "168.3300",
            "5. volume": "29228"
        },
        "2024-05-08 16:00:00": {
            "1. open": "168.1870",
            "2. high": "168.6030",
            "3. low": "167.9530",
            "4. close": "168.2500",
            "5. volume": "1566902"
        },
        "2024-05-08 15:00:00": {
            "1. open": "168.2020",
            "2. high": "168.6030",
            "3. low": "168.0430",
            "4. close": "168.1710",
            "5. volume": "972262"
        },
        "2024-05-08 14:00:00": {
            "1. open": "167.9300",
            "2. high": "168.3060",
            "3. low": "167.9140",
            "4. close": "168.1910",
            "5. volume": "298278"
        },
        "2024-05-08 13:00:00": {
            "1. open": "167.5040",
            "2. high": "167.9000",
            "3. low": "167.3100",
            "4. close": "167.8840",
            "5. volume": "205718"
        },
        "2024-05-08 12:00:00": {
            "1. open": "167.7760",
            "2. high": "167.9000",
            "3. low": "167.0920",
            "4. close": "167.5180",
            "5. volume": "378163"
        },
        "2024-05-08 11:00:00": {
            "1. open": "167.7440",
            "2. high": "167.8900",
            "3. low": "167.4120",
            "4. close": "167.7650",
            "5. volume": "485132"
        },
        "2024-05-08 10:00:00": {
            "1. open": "167.6850",
            "2. high": "167.8600",
            "3. low": "167.2600",
            "4. close": "167.7060",
            "5. volume": "270830"
        },
        "2024-05-08 09:00:00": {
            "1. open": "166.4640",
            "2. high": "167.7320",
            "3. low": "166.2500",
            "4. close": "167.6860",
            "5. volume": "286313"
        },
        "2024-05-08 08:00:00": {
            "1. open": "166.6620",
            "2. high": "167.8500",
            "3. low": "165.6560",
            "4. close": "166.4290",
            "5. volume": "4972"
        },
        "2024-05-08 07:00:00": {
            "1. open": "166.6420",
            "2. high": "167.0580",
            "3. low": "166.6270",
            "4. close": "167.0420",
            "5. volume": "1655"
        },
        "2024-05-08 06:00:00": {
            "1. open": "166.7510",
            "2. high": "166.7510",
            "3. low": "166.6460",
            "4. close": "166.6560",
            "5. volume": "499"
        },
        "2024-05-08 05:00:00": {
            "1. open": "166.7710",
            "2. high": "167.1470",
            "3. low": "166.7450",
            "4. close": "166.7450",
            "5. volume": "35"
        },
        "2024-05-08 04:00:00": {
            "1. open": "166.9390",
            "2. high": "166.9990",
            "3. low": "166.7360",
            "4. close": "166.9830",
            "5. volume": "84"
        },
        "2024-05-07 19:00:00": {
            "1. open": "166.7410",
            "2. high": "167.3350",
            "3. low": "166.7260",
            "4. close": "166.8940",
            "5. volume": "463189"
        },
        "2024-05-07 18:00:00": {
            "1. open": "166.8110",
            "2. high": "166.9100",
            "3. low": "166.5870",
            "4. close": "166.7750",
            "5. volume": "463911"
        },
        "2024-05-07 17:00:00": {
            "1. open": "167.2760",
            "2. high": "167.2760",
            "3. low": "166.7260",
            "4. close": "166.7260",
            "5. volume": "8796"
        },
        "2024-05-07 16:00:00": {
            "1. open": "166.7260",
            "2. high": "167.2960",
            "3. low": "166.0620",
            "4. close": "167.2800",
            "5. volume": "1653795"
        },
        "2024-05-07 15:00:00": {
            "1. open": "166.8650",
            "2. high": "167.0380",
            "3. low": "166.5370",
            "4. close": "166.7110",
            "5. volume": "688074"
        },
        "2024-05-07 14:00:00": {
            "1. open": "166.5430",
            "2. high": "166.9290",
            "3. low": "166.2900",
            "4. close": "166.8350",
            "5. volume": "291817"
        },
        "2024-05-07 13:00:00": {
            "1. open": "166.7810",
            "2. high": "166.9890",
            "3. low": "166.5080",
            "4. close": "166.5170",
            "5. volume": "289271"
        },
        "2024-05-07 12:00:00": {
            "1. open": "166.5530",
            "2. high": "166.8210",
            "3. low": "166.4820",
            "4. close": "166.7750",
            "5. volume": "226260"
        },
        "2024-05-07 11:00:00": {
            "1. open": "167.2760",
            "2. high": "167.3010",
            "3. low": "166.3990",
            "4. close": "166.5330",
            "5. volume": "279151"
        },
        "2024-05-07 10:00:00": {
            "1. open": "167.4250",
            "2. high": "167.6420",
            "3. low": "167.1610",
            "4. close": "167.2310",
            "5. volume": "344360"
        },
        "2024-05-07 09:00:00": {
            "1. open": "167.5340",
            "2. high": "167.7610",
            "3. low": "164.9190",
            "4. close": "167.4780",
            "5. volume": "289921"
        },
        "2024-05-07 08:00:00": {
            "1. open": "167.5530",
            "2. high": "170.3260",
            "3. low": "166.9530",
            "4. close": "167.3400",
            "5. volume": "5594"
        },
        "2024-05-07 07:00:00": {
            "1. open": "167.4540",
            "2. high": "167.5530",
            "3. low": "167.1710",
            "4. close": "167.3790",
            "5. volume": "2309"
        },
        "2024-05-07 06:00:00": {
            "1. open": "167.4350",
            "2. high": "167.5530",
            "3. low": "167.3490",
            "4. close": "167.5380",
            "5. volume": "148"
        },
        "2024-05-07 05:00:00": {
            "1. open": "167.4840",
            "2. high": "167.5530",
            "3. low": "167.1120",
            "4. close": "167.3400",
            "5. volume": "47"
        },
        "2024-05-07 04:00:00": {
            "1. open": "167.0580",
            "2. high": "167.5530",
            "3. low": "166.9530",
            "4. close": "167.5380",
            "5. volume": "1196"
        },
        "2024-05-06 19:00:00": {
            "1. open": "166.9690",
            "2. high": "166.9690",
            "3. low": "166.7450",
            "4. close": "166.9040",
            "5. volume": "747529"
        },
        "2024-05-06 18:00:00": {
            "1. open": "166.9590",
            "2. high": "166.9690",
            "3. low": "166.7450",
            "4. close": "166.9040",
            "5. volume": "747543"
        },
        "2024-05-06 17:00:00": {
            "1. open": "166.9290",
            "2. high": "167.0780",
            "3. low": "166.7450",
            "4. close": "166.8270",
            "5. volume": "808"
        },
        "2024-05-06 16:00:00": {
            "1. open": "166.9790",
            "2. high": "167.2360",
            "3. low": "165.8540",
            "4. close": "166.9140",
            "5. volume": "2366849"
        }
    }
}